name: Bug Report
description: Report a bug in the website or scraper
title: "[Bug] "
labels: ["bug"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Website
        - Scraper
        - Data
        - CI/CD
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What happened? What did you expect?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - OS: Windows 11
        - Browser: Chrome 120
        - Python: 3.11
